name: coursework_pipeline

channels:
  - bioconda
  
dependencies:
  - python=3.8.11
  - snakemake=6.4.1
  - samtools=1.12
  - picard=2.25.6
  - bwa=0.7.17
  - bcftools=1.12
  - trimmomatic=0.39
  - fastqc=0.11.9
  - multiqc=1.10.1
  - gatk4=4.2.0.0
